### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Simplify' not found in /app/code/MasterCard/SimplifyCommerce/lib/SimplifyAdapter.php:36

### ISSUE THREAD

**Issue by kanenas** [simplifycom/simplify-magento-module#10]
**Magento**: 2.3.1
**php**: 7.2.28

**Manual Installation**
Create folder structure inside the the Magento main folder:
`./app/code/MasterCard/SimplifyCommerce`
Extract module files into that folder and execute the following commands:
./bin/magento setup:upgrade
./bin/magento cache:clean

In `Stores > Configuration > Sales > Payment Methods` the method is enabled.
When the modal window pop's up, use some credit card from https://simplify.com/commerce/docs/testing/test-card-numbers and then click to complete the payment, a **500 Error** is generated.

Here is the complete error:
```
PHP Fatal error:  Uncaught Error: Class 'Simplify' not found in /app/code/MasterCard/SimplifyCommerce/lib/SimplifyAdapter.php:36
Stack trace:
#0 /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): MasterCard\SimplifyCommerce\lib\SimplifyAdapter->__construct('xxxxxxxxxx', 'xxxxxxxxxx')
#1 /vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('MasterCard\\Simp...', Array)
#2 /vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('MasterCard\\Simp...', Array)
#3 /app/code/MasterCard/SimplifyCommerce/lib/SimplifyAdapterFactory.php(55): Magento\Framework\ObjectManager\ObjectManager->create('MasterCard\\Simp...', Array)
#4 /home/demosite in /app/code/MasterCard/SimplifyCommerce/lib/SimplifyAdapter.php on line 36
```
Any suggestions?

**Comment by JohnbConneely** [comment]
Hey @kanenas, I see you have two issues raised here. Are they still impacting you? If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route. 

Please provide this thorough information to the support team and they should be able get this moving again if its still happening.
