### ISSUE TITLE
Redriect to admin dashboard on rejected payment.

### ISSUE THREAD

**Issue by MohdAlomar** [simplifycom/simplify-magento-module#11]
If the transaction is rejected by simplify fraud detection the customer will be redirected to admin dashboard.

**Comment by bampisSyk** [comment]
Already faced the same issue and created a pull request with a posible fix

There seems to be a scope change in context, probably due to admin order email procedures.
Moving the cart redirect on top of PlaceOrder controller keeps the redirect scope intact.

**Comment by MohdAlomar** [comment]
> 
> 
> Already faced the same issue and created a pull request with a posible fix
> 
> Pull Request: [b98ed39](https://github.com/simplifycom/simplify-magento-module/commit/b98ed3991075f3a19cd5ba89ec3cc97afc618a52)
> 
> There seems to be a scope change in context, probably due to admin order email procedures.
> Moving the cart redirect on top of PlaceOrder controller keeps the redirect scope intact.

Thank you I applied the fix.
