### ISSUE TITLE
block by x-frame-options policy

### ISSUE THREAD

**Issue by ioweb-gr** [simplifycom/simplify-magento-module#17]
Sometimes on Firefox 77 I receive the error 

```
Blocked by X-Frame-Options Policy
An error occurred during a connection to www.simplify.com 
```

when clicking on the PAY button.

**Comment by JohnbConneely** [comment]
Hey @ioweb-gr, Is this still an issue?

If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.

**Comment by ioweb-gr** [comment]
@JohnbConneely yes the issue still exists and the official channels ignore us completely. That's why we raise them here. You can ask the national bank of Greece why they ignore their customers maybe you'll get a response. However the issues mentioned here do exist and should be looked at imo

**Comment by JohnbConneely** [comment]
Thanks for letting me know @ioweb-gr . I'll try and get these moving the proper paths again.
