### ISSUE TITLE
Message: Mismatched anonymous define() module: function(){return t}

### ISSUE THREAD

**Issue by nicholaskats** [simplifycom/simplify-magento-module#18]
Hello,

We are facing issues in a Magento 2.3.4 installation during checkout. When you click on simplify commerce payment method the following error occurs:

knockout.js:3381 Uncaught Error: Unable to process binding "foreach: function(){return $parent.elems() }"
Message: Unable to process binding "template: function(){return getTemplate() }"
Message: Unable to process binding "if: function(){return (JSON.parse($parent.options).length > 0) }"
Message: Unable to process binding "mageInit: function(){return {'collapsible':{'openedState':'active'}} }"
Message: Mismatched anonymous define() module: function(){return t}

The checkout has been working well for us for a month or so since we installed it, but i guess something changed in https://www.simplify.com/commerce/simplify.pay.js.

If you take a look here in https://www.simplify.com/commerce/simplify.pay.js the following piece of code i guess its the tricky one: define(function(){return t})

Unfortunately, this error breaks the checkout completely, so we had to disable the module and now everything is working well.

**Comment by JohnbConneely** [comment]
Hey @nicholaskats, Is this still an issue? If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route. 

Please provide all of the information you have above too - it will help this get to the correct team quicker.
