### ISSUE TITLE
Debit card support

### ISSUE THREAD

**Issue by sharanyaarun** [simplifycom/simplify-magento-module#19]
Hi,
 It only mentioning about credit cards. What about debit cards?. I have both credit card and debit card payments on my e-commerce site. How to pass debit card data?.

**Comment by JohnbConneely** [comment]
Hey @sharanyaarun, As long as your merchant account supports the card brand, this is not exclusively for credit cards. We will likely change this to say "pay by card" in a future version. 

If you have any follow-up questions, please raise them through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
