### ISSUE TITLE
Payment form is not showing in the checkout page

### ISSUE THREAD

**Issue by rudmarv** [simplifycom/simplify-magento-module#20]
I have successfully  installed the module in app/code and can configure it in back-end dashboard.
But the problem now is that, there is no form for the card credentials in the checkout page.
The radio button is there for the payment method but there is nothing inside of it.

**Comment by JohnbConneely** [comment]
Hey @rudmarv, Is this still an issue? If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
