### ISSUE TITLE
extension not working with Magento 2.3.4 PHP v7.3

### ISSUE THREAD

**Issue by KaranjitGitHub** [simplifycom/simplify-magento-module#21]
Tried installing Simplify magento module on Magento 2.3.4 (have php v7.3) but failed with below error.

[InvalidArgumentException]
  Package mastercard/module-simplifycommerce at version ~3.0.0 has a PHP requirement incompatible with your PHP version (7.3.20)

Any suggestions ?

![unnamed](https://user-images.githubusercontent.com/40873391/89864801-f1e1df80-dbef-11ea-82a6-ff9dc7d0e930.jpg)

**Comment by JohnbConneely** [comment]
Hey @KaranjitGitHub, is this still an issue? If so, could you please raise this through the bank's support team - we'll be able to track your request better. We are going to be closing the issues tab here as we can't track these questions & queries as well as through the regular support route.
