### ISSUE TITLE
Magento 2.2.6 error

### ISSUE THREAD

**Issue by PDimitris** [simplifycom/simplify-magento-module#22]
Hi, i installed the module at my Magento eshop (2.2.6) but when i use Production mode the module doesn't work.

You cannot click the SUBMIT button.

Thank you!
![error1](https://user-images.githubusercontent.com/70693091/92107721-e6e52e00-edee-11ea-9847-3f979214631c.jpg)

**Comment by arrowgr** [comment]
Same issue on 2.2.7

**Comment by ioweb-gr** [comment]
Guys unfortunately the module is not working and it seems the developers in this github channel will only redirect you back to NBG support to get support from the official channel, which official channel will just send canned responses.

We're all in the same spot here and the module is non-working for M2 in pretty much all versions if you run in production mode and it only goes worse as you upgrade Magento 2 through the versions especially with M2.2.x being EOL and 2.3.5p1 / 2.4 forcing a CSP. 

You need to help pressure NBG themselves if you wish to see any type of support and not a vicious loop going back and forth to NBG support and github support. 

If you read on the closed issues you'll see no issue was fixed through reporting it here.

**Comment by JohnbConneely** [comment]
@ioweb-gr @arrowgr @PDimitris the new version has been released. Can you please test and let us know? I'll leave this ticket open for now. 

I have also working on making sure issues reported through the bank are communicated down the line properly, thanks for making us aware.

**Comment by PDimitris** [comment]
Dear @JohnbConneely  now works fine. Thank you!!!
